FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive \
    LC_CTYPE=C.utf8 \
    UV_PROJECT_ENVIRONMENT="/app/.venv" \
    UV_PYTHON_PREFERENCE=system \
    PATH="/app/.venv/bin:$PATH" \
    ENVIRONMENT=dev \
    PYTHONDONTWRITEBYTECODE=1

RUN --mount=type=cache,target=/var/cache/apt,id=apt-cache,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,id=apt-lib,sharing=locked \
    mkdir -p /var/lib/apt/lists/partial && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
        tzdata curl build-essential sqlite3 gosu adduser libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh

WORKDIR /app
